services:
  # Application Service (PHP-FPM)
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: ${APP_NAME:-noon}_app
    restart: unless-stopped
    working_dir: /var/www/html
    volumes:
      - app_storage:/var/www/html/storage
      - .:/var/www/html
    depends_on:
      - db
      - redis # App depends on Redis starting
    networks:
      - noonnet

  # Nginx Web Server Service
  nginx:
    image: nginx:alpine
    container_name: ${APP_NAME:-noon}_nginx
    restart: unless-stopped
    ports:
      - "${APP_PORT:-80}:80"
      - '${VITE_PORT:-5173}:${VITE_PORT:-5173}'
    volumes:
      - .:/var/www/html:ro
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
      - app_storage:/var/www/html/storage:ro
    depends_on:
      - app
    networks:
      - noonnet

  # PostgreSQL Service
  db:
    image: postgres:17.5-alpine
    container_name: ${APP_NAME:-noon}_db
    restart: unless-stopped
    platform: linux/arm64
    environment:
      POSTGRES_DB: ${DB_DATABASE:-note_taking}
      POSTGRES_USER: ${DB_USERNAME:-admin}
      POSTGRES_PASSWORD: ${DB_PASSWORD:-password}
    volumes:
      - db_data:/var/lib/postgresql/data
      - './docker/pgsql/create-testing-database.sql:/docker-entrypoint-initdb.d/10-create-testing-database.sql'
    ports:
      - "${DB_FORWARD_PORT:-5432}:5432" # Forward port for external connections if needed
    networks:
      - noonnet
    healthcheck:
        test: ["CMD-SHELL", "pg_isready -U ${DB_USERNAME:-admin} -d ${DB_DATABASE:-noon}"]
        interval: 10s
        timeout: 5s
        retries: 5

  # Redis Service
  redis:
    image: redis:alpine
    container_name: ${APP_NAME:-noon}_redis
    restart: unless-stopped
    volumes:
      - redis_data:/data # Persist Redis data
    ports:
      # Forward port for external connections if needed (e.g., debugging)
      - "${REDIS_FORWARD_PORT:-6379}:6379"
    networks:
      - noonnet
    healthcheck:
        test: ["CMD", "redis-cli", "ping"]
        interval: 10s
        timeout: 5s
        retries: 5

# Docker Networks
networks:
  noonnet:
    driver: bridge

# Docker Volumes (for data persistence)
volumes:
  db_data:
    driver: local
  redis_data:
    driver: local
  app_storage:
    driver: local
